# Generated by Django 5.2.1 on 2025-12-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('qr_token', models.CharField(blank=True, max_length=200, null=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
