# Generated by Django 5.2.1 on 2025-12-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_nightpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('scanned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='nightpass',
            old_name='is_used',
            new_name='verified',
        ),
        migrations.RemoveField(
            model_name='nightpass',
            name='qr_token',
        ),
        migrations.AddField(
            model_name='nightpass',
            name='qr_code_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
