# Generated by Django 5.2.1 on 2025-12-02 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_qrcode_rename_is_used_nightpass_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
        migrations.RemoveField(
            model_name='nightpass',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='nightpass',
            name='qr_code_file',
        ),
        migrations.RemoveField(
            model_name='nightpass',
            name='year',
        ),
        migrations.AddField(
            model_name='nightpass',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nightpass',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
