# Generated by Django 5.2.1 on 2025-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_delete_qrcode_remove_nightpass_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nightpass',
            old_name='qr_code_image',
            new_name='qr_code_file',
        ),
        migrations.RemoveField(
            model_name='nightpass',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='nightpass',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
