# Generated by Django 5.2.1 on 2025-12-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_faculty_department_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='first_place',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='second_place',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='third_place',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='winner',
            name='first_winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='second_winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='third_winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
